/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaPrincipal.java
 *
 * Created on 09/05/2012, 11:20:15
 */
package br.ufrn.dimap.interfaceGrafica;

import br.ufrn.dimap.Grafo.Aresta;
import br.ufrn.dimap.Grafo.Grafo;
import br.ufrn.dimap.Grafo.GrafoLista;
import br.ufrn.dimap.Grafo.GrafoMatriz;
import br.ufrn.dimap.Grafo.Vertice;
import br.ufrn.dimap.Grafo.excecoes.ListaDeVerticesCheiaException;
import br.ufrn.dimap.Grafo.excecoes.ParDeVerticesNaoExistenteException;
import br.ufrn.dimap.Grafo.excecoes.VerticeJaExisteException;
import br.ufrn.dimap.Grafo.excecoes.VerticeNaoExisteException;
import br.ufrn.dimap.interfaceGrafica.resources.background;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Anthonini
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    private Grafo grafo;
    private LinkedList<JLabel> jLabels;
    private PainelAux Painel1;
    private background background;

    /** Creates new form JanelaPrincipal */
    public JanelaPrincipal() {
        background = new background("fundo.png");
        this.setContentPane(background);
        initComponents();
        initComponentsAdicionais();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        criarGrafoJanela = new javax.swing.JDialog();
        listaRButton = new javax.swing.JRadioButton();
        matrizRButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        okButtonCGJ = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tamanhoGrafoText = new javax.swing.JFormattedTextField();
        adicionarArestaJanela = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        okButtonARA = new javax.swing.JButton();
        cancelButtonARA = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        verticeInicial = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        verticeFinal = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        pesoText = new javax.swing.JFormattedTextField();
        dirigida = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        removerArestaJanela = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        okButtonARA1 = new javax.swing.JButton();
        cancelButtonARA1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        verticeInicialRemover = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        verticeFinalRemover = new javax.swing.JFormattedTextField();
        adicionarRemoverVertice = new javax.swing.JDialog();
        verticeOperacao = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idText = new javax.swing.JFormattedTextField();
        adicionarRemoverVerticeButton = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        noPadrao = new javax.swing.JLabel();
        noPercurso = new javax.swing.JLabel();
        fundo = new javax.swing.JPanel();
        botoesPanel = new javax.swing.JPanel();
        criarGrafoButton = new javax.swing.JButton();
        adicionarVerticeButton = new javax.swing.JButton();
        removerVerticeButton = new javax.swing.JButton();
        adicionarArestaButton = new javax.swing.JButton();
        removerArestaButton = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jscrollPaneArestas = new javax.swing.JScrollPane();
        verticesPanel = new javax.swing.JPanel();

        criarGrafoJanela.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        criarGrafoJanela.setTitle("Criação de Grafo");
        criarGrafoJanela.setMinimumSize(new java.awt.Dimension(311, 231));
        criarGrafoJanela.setResizable(false);

        buttonGroup1.add(listaRButton);
        listaRButton.setSelected(true);
        listaRButton.setText("Como Lista");
        listaRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaRButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(matrizRButton);
        matrizRButton.setText("Como Matriz");
        matrizRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizRButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Criar Novo Grafo Como:");

        okButtonCGJ.setText("Ok");
        okButtonCGJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonCGJActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Tamanho:");

        tamanhoGrafoText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        javax.swing.GroupLayout criarGrafoJanelaLayout = new javax.swing.GroupLayout(criarGrafoJanela.getContentPane());
        criarGrafoJanela.getContentPane().setLayout(criarGrafoJanelaLayout);
        criarGrafoJanelaLayout.setHorizontalGroup(
            criarGrafoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criarGrafoJanelaLayout.createSequentialGroup()
                .addGroup(criarGrafoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criarGrafoJanelaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(criarGrafoJanelaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(criarGrafoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listaRButton)
                            .addGroup(criarGrafoJanelaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tamanhoGrafoText, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(matrizRButton)
                            .addGroup(criarGrafoJanelaLayout.createSequentialGroup()
                                .addComponent(okButtonCGJ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        criarGrafoJanelaLayout.setVerticalGroup(
            criarGrafoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criarGrafoJanelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(listaRButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(matrizRButton)
                .addGap(13, 13, 13)
                .addGroup(criarGrafoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tamanhoGrafoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(criarGrafoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButtonCGJ)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adicionarArestaJanela.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        adicionarArestaJanela.setTitle("Arestas");
        adicionarArestaJanela.setMinimumSize(new java.awt.Dimension(311, 231));
        adicionarArestaJanela.setResizable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Criar Nova Aresta Entre:");

        okButtonARA.setText("Adicionar");
        okButtonARA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonARAActionPerformed(evt);
            }
        });

        cancelButtonARA.setText("Fechar");
        cancelButtonARA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonARAActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Vertice Inicial:");

        verticeInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Vertice Final:");

        verticeFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setText("Peso:");

        pesoText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        dirigida.setFont(new java.awt.Font("Tahoma", 1, 11));
        dirigida.setText("Dirigida");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setText("Tipo:");

        javax.swing.GroupLayout adicionarArestaJanelaLayout = new javax.swing.GroupLayout(adicionarArestaJanela.getContentPane());
        adicionarArestaJanela.getContentPane().setLayout(adicionarArestaJanelaLayout);
        adicionarArestaJanelaLayout.setHorizontalGroup(
            adicionarArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adicionarArestaJanelaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(adicionarArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adicionarArestaJanelaLayout.createSequentialGroup()
                        .addComponent(okButtonARA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButtonARA))
                    .addGroup(adicionarArestaJanelaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verticeInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adicionarArestaJanelaLayout.createSequentialGroup()
                        .addGroup(adicionarArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(adicionarArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pesoText, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verticeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dirigida)))
                    .addComponent(jLabel3))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        adicionarArestaJanelaLayout.setVerticalGroup(
            adicionarArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adicionarArestaJanelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(adicionarArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verticeInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adicionarArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verticeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adicionarArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adicionarArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dirigida))
                .addGap(18, 18, 18)
                .addGroup(adicionarArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButtonARA)
                    .addComponent(cancelButtonARA))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        removerArestaJanela.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        removerArestaJanela.setTitle("Arestas");
        removerArestaJanela.setMinimumSize(new java.awt.Dimension(311, 231));
        removerArestaJanela.setResizable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText("Remover Aresta Entre:");

        okButtonARA1.setText("Remover");
        okButtonARA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonARA1ActionPerformed(evt);
            }
        });

        cancelButtonARA1.setText("Cancelar");
        cancelButtonARA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonARA1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setText("Vertice Inicial:");

        verticeInicialRemover.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("Vertice Final:");

        verticeFinalRemover.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        javax.swing.GroupLayout removerArestaJanelaLayout = new javax.swing.GroupLayout(removerArestaJanela.getContentPane());
        removerArestaJanela.getContentPane().setLayout(removerArestaJanelaLayout);
        removerArestaJanelaLayout.setHorizontalGroup(
            removerArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removerArestaJanelaLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(okButtonARA1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButtonARA1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removerArestaJanelaLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(removerArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(removerArestaJanelaLayout.createSequentialGroup()
                        .addGroup(removerArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(removerArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verticeFinalRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verticeInicialRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(95, 95, 95))
        );
        removerArestaJanelaLayout.setVerticalGroup(
            removerArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removerArestaJanelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addGroup(removerArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verticeInicialRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(removerArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verticeFinalRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(removerArestaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButtonARA1)
                    .addComponent(cancelButtonARA1))
                .addGap(22, 22, 22))
        );

        adicionarRemoverVertice.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        adicionarRemoverVertice.setTitle("Vértices");
        adicionarRemoverVertice.setMinimumSize(new java.awt.Dimension(217, 147));
        adicionarRemoverVertice.setResizable(false);

        verticeOperacao.setFont(new java.awt.Font("Tahoma", 1, 11));
        verticeOperacao.setText("Adicionar Vértice:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("ID: ");

        idText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        adicionarRemoverVerticeButton.setText("Adicionar Vértice");
        adicionarRemoverVerticeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarRemoverVerticeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adicionarRemoverVerticeLayout = new javax.swing.GroupLayout(adicionarRemoverVertice.getContentPane());
        adicionarRemoverVertice.getContentPane().setLayout(adicionarRemoverVerticeLayout);
        adicionarRemoverVerticeLayout.setHorizontalGroup(
            adicionarRemoverVerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adicionarRemoverVerticeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(verticeOperacao)
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(adicionarRemoverVerticeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adicionarRemoverVerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adicionarRemoverVerticeLayout.createSequentialGroup()
                        .addComponent(adicionarRemoverVerticeButton)
                        .addContainerGap())
                    .addGroup(adicionarRemoverVerticeLayout.createSequentialGroup()
                        .addComponent(idText, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addGap(97, 97, 97))))
        );
        adicionarRemoverVerticeLayout.setVerticalGroup(
            adicionarRemoverVerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adicionarRemoverVerticeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verticeOperacao)
                .addGap(18, 18, 18)
                .addGroup(adicionarRemoverVerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(adicionarRemoverVerticeButton)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        noPadrao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/dimap/interfaceGrafica/resources/noPadrao.png"))); // NOI18N

        noPercurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/dimap/interfaceGrafica/resources/noPercurso.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interface Gráfica para Grafos - Versão Beta");

        fundo.setBackground(new java.awt.Color(0, 0, 0));
        fundo.setOpaque(false);

        botoesPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botoesPanel.setOpaque(false);

        criarGrafoButton.setText("Criar Novo Grafo");
        criarGrafoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarGrafoButtonActionPerformed(evt);
            }
        });

        adicionarVerticeButton.setText("Adicionar Vertice");
        adicionarVerticeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarVerticeButtonActionPerformed(evt);
            }
        });

        removerVerticeButton.setText("Remover Vertice");
        removerVerticeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerVerticeButtonActionPerformed(evt);
            }
        });

        adicionarArestaButton.setText("Adicionar Aresta");
        adicionarArestaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarArestaButtonActionPerformed(evt);
            }
        });

        removerArestaButton.setText("Remover Aresta");
        removerArestaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerArestaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botoesPanelLayout = new javax.swing.GroupLayout(botoesPanel);
        botoesPanel.setLayout(botoesPanelLayout);
        botoesPanelLayout.setHorizontalGroup(
            botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(criarGrafoButton)
                .addGap(18, 18, 18)
                .addComponent(adicionarVerticeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removerVerticeButton)
                .addGap(8, 8, 8)
                .addComponent(adicionarArestaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerArestaButton)
                .addGap(50, 50, 50))
        );
        botoesPanelLayout.setVerticalGroup(
            botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criarGrafoButton)
                    .addComponent(adicionarVerticeButton)
                    .addComponent(adicionarArestaButton)
                    .addComponent(removerVerticeButton)
                    .addComponent(removerArestaButton))
                .addContainerGap())
        );

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jscrollPaneArestas.setBackground(new java.awt.Color(0, 0, 0));
        jscrollPaneArestas.setOpaque(false);
        jscrollPaneArestas.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                jscrollPaneArestasAncestorResized(evt);
            }
        });
        jscrollPaneArestas.setBounds(0, 0, 669, 427);
        jLayeredPane1.add(jscrollPaneArestas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        verticesPanel.setBackground(new java.awt.Color(0, 0, 0));
        verticesPanel.setOpaque(false);
        verticesPanel.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                verticesPanelAncestorResized(evt);
            }
        });

        javax.swing.GroupLayout verticesPanelLayout = new javax.swing.GroupLayout(verticesPanel);
        verticesPanel.setLayout(verticesPanelLayout);
        verticesPanelLayout.setHorizontalGroup(
            verticesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        verticesPanelLayout.setVerticalGroup(
            verticesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        verticesPanel.setBounds(0, 0, -1, -1);
        jLayeredPane1.add(verticesPanel, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botoesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addComponent(botoesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criarGrafoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarGrafoButtonActionPerformed
        criarGrafoJanela.setVisible(true);
    }//GEN-LAST:event_criarGrafoButtonActionPerformed

    private void okButtonCGJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonCGJActionPerformed
        String tipoGrafo;
        if (listaRButton.isSelected()) {
            tipoGrafo = "Como Lista";
        } else {
            tipoGrafo = "Como Matriz";
        }
        if (tamanhoGrafoText.getText().compareToIgnoreCase("") != 0 || tipoGrafo.compareTo("Como Lista") == 0) {
            if (tipoGrafo.compareToIgnoreCase("Como Matriz") == 0) {
                grafo = new GrafoMatriz(Integer.parseInt(tamanhoGrafoText.getText()));
            } else {
                grafo = new GrafoLista();
            }
            this.verticesPanel.removeAll();
            jscrollPaneArestas.setViewportView(null);
            jLabels.removeAll(jLabels);
            this.criarGrafoJanela.dispose();
        } else {
            JOptionPane.showMessageDialog(criarGrafoJanela, "Digite um tamanho para o Grafo", "Criação de Grafo", 1);
        }
    }//GEN-LAST:event_okButtonCGJActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        criarGrafoJanela.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void adicionarVerticeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarVerticeButtonActionPerformed
        if (grafo != null) {
            verticeOperacao.setText("Adicionar Vértice");
            adicionarRemoverVerticeButton.setText("Adicionar Vértice");
            adicionarRemoverVertice.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(criarGrafoJanela, "Grafo ainda não criado", "Adicionar Vertice", 1);
        }
    }//GEN-LAST:event_adicionarVerticeButtonActionPerformed

    private void adicionarArestaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarArestaButtonActionPerformed
        if (grafo != null) {
            adicionarArestaJanela.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(adicionarArestaJanela, "Grafo Ainda não Criado", "Adicionar Aresta", 1);
        }
    }//GEN-LAST:event_adicionarArestaButtonActionPerformed

    private void okButtonARAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonARAActionPerformed
        adicionarAresta();
    }//GEN-LAST:event_okButtonARAActionPerformed

    private void removerArestaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerArestaButtonActionPerformed
        if (grafo != null) {
            removerArestaJanela.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(removerArestaJanela, "Grafo Ainda não Criado", "Remover Aresta", 1);
        }
    }//GEN-LAST:event_removerArestaButtonActionPerformed

    private void jscrollPaneArestasAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jscrollPaneArestasAncestorResized
        this.jscrollPaneArestas.setSize(jLayeredPane1.getSize().width, jLayeredPane1.getSize().height);
    }//GEN-LAST:event_jscrollPaneArestasAncestorResized

    private void verticesPanelAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_verticesPanelAncestorResized
        this.verticesPanel.setSize(jLayeredPane1.getSize().width, jLayeredPane1.getSize().height);
    }//GEN-LAST:event_verticesPanelAncestorResized

    private void matrizRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizRButtonActionPerformed
        jLabel2.setVisible(true);
        tamanhoGrafoText.setVisible(true);
    }//GEN-LAST:event_matrizRButtonActionPerformed

    private void listaRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaRButtonActionPerformed
        jLabel2.setVisible(false);
        tamanhoGrafoText.setVisible(false);
    }//GEN-LAST:event_listaRButtonActionPerformed

    private void removerVerticeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerVerticeButtonActionPerformed
        if (grafo != null) {
            adicionarRemoverVerticeButton.setText("Remover Vértice");
            verticeOperacao.setText("Remover Vértice");
            adicionarRemoverVertice.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(criarGrafoJanela, "Grafo ainda não criado", "Adicionar Vertice", 1);
        }
    }//GEN-LAST:event_removerVerticeButtonActionPerformed

    private void adicionarRemoverVerticeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarRemoverVerticeButtonActionPerformed
        if (verticeOperacao.getText().startsWith("Adicionar")) {
            adicionarVertice();
        } else {
            removerVertice();
        }
    }//GEN-LAST:event_adicionarRemoverVerticeButtonActionPerformed

    private void cancelButtonARAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonARAActionPerformed
        adicionarArestaJanela.dispose();
}//GEN-LAST:event_cancelButtonARAActionPerformed

    private void okButtonARA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonARA1ActionPerformed
        removerAresta();
    }//GEN-LAST:event_okButtonARA1ActionPerformed

    private void cancelButtonARA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonARA1ActionPerformed
        removerArestaJanela.dispose();
    }//GEN-LAST:event_cancelButtonARA1ActionPerformed

    private void adicionarVertice() {
        try {
            String number = idText.getText();
            if (number.compareTo("") != 0) {
                grafo.inserirVertice( new Vertice(Integer.parseInt(number)) );
                adicionarVerticeNaTela(number);
            }
        } catch (ListaDeVerticesCheiaException e) {
            JOptionPane.showMessageDialog(criarGrafoJanela, "Grafo Completo", "Adicionar Vertice", 1);
        } catch (VerticeJaExisteException e) {
            JOptionPane.showMessageDialog(criarGrafoJanela, "Vértice Com Esse Número já Existente", "Adicionar Vertice", 1);
        }
    }

    private void adicionarAresta() {
        if (verticeInicial.getText().compareToIgnoreCase("") != 0 && verticeFinal.getText().compareToIgnoreCase("") != 0) {
            Integer verticeOrigemId = Integer.parseInt(verticeInicial.getText());
            Integer verticeDestinoId = Integer.parseInt(verticeFinal.getText());
            Vertice origem = grafo.buscarVertice(verticeOrigemId);
            Vertice destino = grafo.buscarVertice(verticeDestinoId);
            int peso = 0;
            if (pesoText.getText().compareTo("") != 0) {
                peso = Integer.parseInt(pesoText.getText());
            }            
            if (origem != null && destino != null) {
                try{
                if (dirigida.isSelected()) {                    
                    grafo.inserirAresta(new Aresta( origem, destino ) );
                } else {
                    grafo.inserirAresta(new Aresta( origem, destino ) );
                }
                adicionarArestasNaTela();
                }
                catch( ParDeVerticesNaoExistenteException e ){
                    JOptionPane.showMessageDialog(adicionarArestaJanela, "Vertice Inicial ou Final não Existente", "Adicionar Aresta", 1);
                }
            } else {
                JOptionPane.showMessageDialog(adicionarArestaJanela, "Vertice Inicial ou Final não Existente", "Adicionar Aresta", 1);
            }
        }
    }

    private void removerAresta() {
        if (verticeInicialRemover.getText().compareToIgnoreCase("") != 0 && verticeFinalRemover.getText().compareToIgnoreCase("") != 0) {
            Integer verticeInicialId = Integer.parseInt(verticeInicialRemover.getText());
            Integer verticeFinalId = Integer.parseInt(verticeFinalRemover.getText());            
            try{
                grafo.removerAresta(verticeInicialId, verticeFinalId);
                adicionarArestasNaTela();
            }catch( ParDeVerticesNaoExistenteException e){
                JOptionPane.showMessageDialog(adicionarArestaJanela, "Vertice Inicial ou Final não Existente", "Adicionar Aresta", 1);
            }
        }
    }

    private void removerVertice() {
        String idTexto = idText.getText();
        if (idTexto.compareTo("") != 0) {
            try{
                int indice =  grafo.buscarPosicaoVertice(Integer.parseInt(idTexto));
                grafo.removerVertice(Integer.parseInt(idTexto));                
                jLabels.remove(indice);
                verticesPanel.remove(indice);
                verticesPanel.repaint();
                adicionarArestasNaTela();
            }catch(VerticeNaoExisteException e){
                JOptionPane.showMessageDialog(criarGrafoJanela, "Vértice com Id = " +e.getId()+" não existente!", "Remover Vertice", 1);
            }
        } else {
            JOptionPane.showMessageDialog(criarGrafoJanela, "Digite um Número", "Remover Vertice", 1);
        }
    }

    private void adicionarVerticeNaTela(String valor) {
        JLabel a = new JLabel();
        this.verticesPanel.add(a);
        a.setLocation(10, 10);
        a.validate();
        a.setSize(79, 73);
        a.setIcon(noPadrao.getIcon());
        JLabel b = new JLabel();
        a.add(b);
        b.setLocation(0, -5);
        b.setHorizontalAlignment(0);
        b.setForeground(Color.white);
        b.setFont(new java.awt.Font("Tahoma", 1, 11));
        b.validate();
        b.setSize(69, 69);
        b.setText(valor);

        a.addMouseListener(new clicaMouse());
        a.addMouseMotionListener(new ArrastarMouse(this));
        a.setVisible(true);
        jLabels.add(a);
    }

    public void adicionarArestasNaTela() {
        Painel1 = new PainelAux();
        Painel1.setOpaque(false);
        jscrollPaneArestas.setViewportView(Painel1);
        Color cor = Color.red;

        Iterator<Aresta> arestas = grafo.obterArestas();
        Aresta arestaAtual;
        int x1, y1, x2, y2;
        JLabel origem, destino;

        while (arestas.hasNext()) {
            arestaAtual = arestas.next();
            int origemIndice = grafo.buscarPosicaoVertice(arestaAtual.getOrigem().getId());
            int destinoIndice = grafo.buscarPosicaoVertice(arestaAtual.getDestino().getId());

            origem = jLabels.get(origemIndice);
            destino = jLabels.get(destinoIndice);
            x1 = origem.getX() + 35;
            y1 = origem.getY() + 35;
            x2 = destino.getX() + 35;
            y2 = destino.getY() + 35;

            Painel1.addAresta(x1, y1, x2, y2, cor, Painel1.getGraphics());
        }
        Painel1.paintComponent(Painel1.getGraphics());
        jscrollPaneArestas.setVisible(true);
    }

    private void initComponentsAdicionais() {
        jLabels = new LinkedList();
        this.setLocationRelativeTo(null);
        this.setSize(669, 476);
        this.jscrollPaneArestas.getViewport().setOpaque(false);

        jLabel2.setVisible(false);
        tamanhoGrafoText.setVisible(false);

        criarGrafoJanela.setLocationRelativeTo(null);
        adicionarArestaJanela.setLocationRelativeTo(null);
        adicionarRemoverVertice.setLocationRelativeTo(null);
        removerArestaJanela.setLocationRelativeTo(null);

    }  

    

    class clicaMouse extends MouseAdapter {
        @Override
        public void mousePressed(MouseEvent e) {
            point.x = e.getX();
            point.y = e.getY();
        }
    }

    class ArrastarMouse extends MouseMotionAdapter {
        private JanelaPrincipal jp;
        public ArrastarMouse(JanelaPrincipal jp) {
            this.jp = jp;
        }
        @Override
        public void mouseDragged(MouseEvent e) {
            Point p = ((JLabel) e.getSource()).getLocation();
            ((JLabel) e.getSource()).setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
            int x = ((JLabel) e.getSource()).getLocation().x;
            int y = ((JLabel) e.getSource()).getLocation().y;
            if (((x > jp.getWidth() - 82) && (y > jp.getHeight() - 145))) {
                ((JLabel) e.getSource()).setLocation(jp.getWidth() - 82, jp.getHeight() - 145);
            } else {
                if (((x < 0) && (y > jp.getHeight() - 145))) {
                    ((JLabel) e.getSource()).setLocation(0, jp.getHeight() - 145);
                } else {
                    if (((x > jp.getWidth() - 82) && (y < 2))) {
                        ((JLabel) e.getSource()).setLocation(jp.getWidth() - 82, 2);
                    } else {
                        if (((x < 0) && (y < 2))) {
                            ((JLabel) e.getSource()).setLocation(0, 2);
                        }                       
                        else {
                            if (y > jp.getHeight() - 145) {
                                ((JLabel) e.getSource()).setLocation(p.x + e.getX() - point.x, jp.getHeight() - 145);
                            } else {
                                if (x > jp.getWidth() - 82) {
                                    ((JLabel) e.getSource()).setLocation(jp.getWidth() - 82, p.y + e.getY() - point.y);
                                } else {
                                    if (y < 2) {
                                        ((JLabel) e.getSource()).setLocation(p.x + e.getX() - point.x, 2);
                                    } else {
                                        if (x < 0) {
                                            ((JLabel) e.getSource()).setLocation(0, p.y + e.getY() - point.y);
                                        } else {
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

            jp.adicionarArestasNaTela();
        }
    }

    private static class DefaultCloseJDialog extends WindowAdapter {
        JanelaPrincipal jp;
        public DefaultCloseJDialog(JanelaPrincipal jp) {
            this.jp = jp;
        }
        @Override
        public void windowClosed(WindowEvent e) {
            jp.setEnabled(true);
            jp.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            System.out.println("Error setting native LAF: " + e);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }
    private static Point point = new Point();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarArestaButton;
    private javax.swing.JDialog adicionarArestaJanela;
    private javax.swing.JDialog adicionarRemoverVertice;
    private javax.swing.JButton adicionarRemoverVerticeButton;
    private javax.swing.JButton adicionarVerticeButton;
    private javax.swing.JPanel botoesPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButtonARA;
    private javax.swing.JButton cancelButtonARA1;
    private javax.swing.JButton criarGrafoButton;
    private javax.swing.JDialog criarGrafoJanela;
    private javax.swing.JCheckBox dirigida;
    private javax.swing.JPanel fundo;
    private javax.swing.JFormattedTextField idText;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jscrollPaneArestas;
    private javax.swing.JRadioButton listaRButton;
    private javax.swing.JRadioButton matrizRButton;
    private javax.swing.JLabel noPadrao;
    private javax.swing.JLabel noPercurso;
    private javax.swing.JButton okButtonARA;
    private javax.swing.JButton okButtonARA1;
    private javax.swing.JButton okButtonCGJ;
    private javax.swing.JFormattedTextField pesoText;
    private javax.swing.JButton removerArestaButton;
    private javax.swing.JDialog removerArestaJanela;
    private javax.swing.JButton removerVerticeButton;
    private javax.swing.JFormattedTextField tamanhoGrafoText;
    private javax.swing.JFormattedTextField verticeFinal;
    private javax.swing.JFormattedTextField verticeFinalRemover;
    private javax.swing.JFormattedTextField verticeInicial;
    private javax.swing.JFormattedTextField verticeInicialRemover;
    private javax.swing.JLabel verticeOperacao;
    private javax.swing.JPanel verticesPanel;
    // End of variables declaration//GEN-END:variables
}
